### ISSUE TITLE
Fontの実装方法

### ISSUE THREAD

**Issue by kojitaniguchi** [hanahana11/nanairo#1]
# 実装手順
## 1. 下の写真の様に、fontフォルダを作って、その中にuraraフォントを移動させる
![image](https://user-images.githubusercontent.com/19344403/64234609-aaf46000-cf31-11e9-8841-55bcec0e9970.png)
## 2. CSSにfont-faceを定義する
```css:style.css
@font-face {
  font-family: "Urara";
  src: url('./font/Urara-H.otf')
}

h1 {
    color: #020000;
    font-size: 90px;
     /* ↓ここをUraraに変える！↓ */
    font-family: "Urara";
    /*
    border-style: solid;
    border-width: 10px;
    border-color: white;
    */
    text-align: center;
    padding: 30px;
    margin: 20px;
    border-radius: 90px;
}
```
font-faceはcssで自分の使いたいフォントを使うために必要なものだよ

## 3. 絆が消えた...
![image](https://user-images.githubusercontent.com/19344403/64235036-7df47d00-cf32-11e9-8d09-d556c4978b4d.png)
↓
絆が消えちゃったね...。
Uraraフォントはひらがなにしか対応してないから漢字消えちゃったわけだ....

### 対応策はね
1. 全てひらがなにする
2. 漢字も対応するフォントを探す

になります！
