### ISSUE TITLE
写真のアニメーションの修正

### ISSUE THREAD

**Issue by kojitaniguchi** [hanahana11/nanairo#2]
# 手順
## 1. cssを以下の様に修正する
```css
#photo-collection {
    height: 440px;
    font-size: 30px;
    background-color: #ffffff;
    padding: 20px;
    border-radius: 30px;
    /* text-align: center;*/
}

.photo-show {
    height: 440px;
    /*表示したい大きさ*/
    width: 440px;
    /*表示したい大きさ、height と合わせる*/

    margin: 30px auto;
    /*縦余白30pxは任意*/
    max-width: 100%;
    position: relative;
}

.photo-show img {
    height: 440px;
    /*表示したい大きさ*/
    width: 440px;
    /*表示したい大きさ、height と合わせる*/

    animation: show 16s infinite;
    -webkit-animation: show 16s infinite;
    border-radius: 50%;
　 /*↓これを消してほしい！！！↓*/
    height: auto;
    /*↑ これを消してほしい！！！ ↑*/
    max-width: 100%;
    opacity: 0;
    position: absolute;
    /*画像を全て重ねる*/
}
```

## 2. こんな感じになるはず
![image](https://user-images.githubusercontent.com/19344403/64236543-90bc8100-cf35-11e9-9629-3cb2023a0162.png)

## 追記
上のcssの `.photo-show img` の `height: auto;` を消してみてほしいです！！！
