### ISSUE TITLE
水玉背景画像

### ISSUE THREAD

**Issue by kojitaniguchi** [hanahana11/nanairo#3]
- [x] 水玉の背景画像の作成する
- [x] 実装する

## CSSを変更する
今は、`.part` に背景画像を設定しているから、他のセクションの背景も水玉になってしまっているね
なので、 `.about` っていうクラスを作って、`.part`も合わせて以下のように修正しよう！
### 変更前
https://github.com/hanahana11/nanairo/blob/fd0ce37f51b5c1e82f28739c2a7d629a11cd92c6/%E6%9C%AB%E5%88%A9%E8%8A%B1_%E3%83%8F%E3%83%8A/stylesheet.css#L55-L65
### 変更後
```css
.about {
    color: #663300;
    padding: 0.5em 1em;
    background-image: url(img/mizutama.JPEG);
    background-size: cover;
    background-repeat: no-repeat;
}

.part {
    color: #663300;
    padding: 0.5em 1em;
    margin: 2em 0;
    background: -webkit-repeating-linear-gradient(-45deg, #f0f8ff, #f0f8ff 3px,#e9f4ff 3px, #e9f4ff 7px);
    background: repeating-linear-gradient(-45deg, #f0f8ff, #f0f8ff 3px,#e9f4ff 3px, #e9f4ff 7px);
}
```
photoも同様に、以下のように修正しよう！
### 変更前
https://github.com/hanahana11/nanairo/blob/fd0ce37f51b5c1e82f28739c2a7d629a11cd92c6/%E6%9C%AB%E5%88%A9%E8%8A%B1_%E3%83%8F%E3%83%8A/stylesheet.css#L153-L165
### 変更後
```css
.photo {
    color: #663300;
    background-color: white;
    padding: 30px;
    padding: 0.5em 1em;
    margin: 2em 0;
    font-family: "elemerfont";
    background: -webkit-repeating-linear-gradient(-45deg, #f0f8ff, #f0f8ff 3px,#e9f4ff 3px, #e9f4ff 7px);
    background: repeating-linear-gradient(-45deg, #f0f8ff, #f0f8ff 3px,#e9f4ff 3px, #e9f4ff 7px);
}
```
## htmlを編集する
さっき定義した、cssをhtmlに当てるために、classを以下のように修正しよう！
### 変更前
https://github.com/hanahana11/nanairo/blob/fd0ce37f51b5c1e82f28739c2a7d629a11cd92c6/%E6%9C%AB%E5%88%A9%E8%8A%B1_%E3%83%8F%E3%83%8A/index.html#L25-L36
### 変更後
```html
   <section class="about" id="about"> ←ここをaboutにする
      <h2 class="title">なないろの絆は</h2>
      <p class="nanairo">
          色々な特性を持ったみんなが色々な色を放ち、<br>
          綺麗な虹のように輝いてほしい<br>
          と、願っています。
      </p>
  </section>
```
