### ISSUE TITLE
レスポンシブ化

### ISSUE THREAD

**Issue by kojitaniguchi** [hanahana11/nanairo#9]
### 1. headタグに `viewport` 追加する
```html
<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
```

### 2. cssにスマホ用のメディアクエリーを追加
```css
@media screen and (max-width:480px) {
    nav {
        float: right;
        padding: 20px;
    }

    nav li {
        font-size: 14px;
        margin-right: 16px;
        display: inline-block;
    }
}
```
